### ISSUE TITLE
Cant load piper Cub after upgrading to aerofly_fs_2_update_v2040731

### ISSUE THREAD

**Issue by rdzielicki** [krzysk1/pipercub#11]
Hello,

I love this aircraft and your job;-)
 since update v2040731; aircraft can be selected but when started it swap to Cesna or other aircraft; guess it is because of update; uninstall and update AS_AEROFLY_FS_2_UPDATE_V2040315 is the only workaround.

**Comment by krzysk1** [comment]
na
