### ISSUE TITLE
Engine Idles at too high an RPM

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/pipercub#12]
Currently the engine idles at 800 RPM. This is too high because it causes the aircraft to move when on the tarmac unless brakes are constantly applied (no parking brake is available). Also when landing, idle engine throttle setting keeps the aircraft from slowing down for a long long time, and you cannot apply brakes because at 18 knots you will nose over onto the tarmac.

![20230218045130_1](https://user-images.githubusercontent.com/69315126/219867150-c101586b-2222-4bcb-bee1-a4179b43e2a5.jpg)

Current 800 RPM setting: <[float64][ThrottleIdle][0.24]>
500 RPM setting: <[float64][ThrottleIdle][0.175]>  
250 RPM setting:  <[float64][ThrottleIdle][0.12]>    
However, you also either need to increase the ground rolling resistance of the wheels or maybe reduce the propeller pitch (not sure which) otherwise you still get a slight forward movement on the tarmac.

**Comment by krzysk1** [comment]
I set <[float64][ThrottleIdle][0.185]> ie 550 RPM. I have found that 550 to 600 rpm at static idle is about right.

https://pietenpols.org/forum/viewtopic.php?t=38780
