### ISSUE TITLE
The cold and dark and before engine start presets not correct

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/pipercub#13]
The pipercub_start.tmd and pipercub_cold.tmd preset files are not correct in that the engine is always running when selecting these two starting conditions.

**Comment by jayeye2011** [comment]
Here are the corrected pipercub_cold.tmd and pipercub_start.tmd preset files so that the engine is not running when these startup modes are selected.
[corrected pipercub start&cold&dark presets.zip](https://github.com/krzysk1/pipercub/files/10788053/corrected.pipercub.start.cold.dark.presets.zip)

**Comment by krzysk1** [comment]
thanks for corrected files. I fully adopted them
