### ISSUE TITLE
door closing

### ISSUE THREAD

**Issue by HerveF2** [krzysk1/pipercub#3]
Hi ! I'm unable to close the door, once opened ! How to proceed ? Thx

**Comment by jayeye2011** [comment]
@krzysk1 Any chance you could fix this. Maybe define another control input area that will close the door if it is open when activated?

**Comment by krzysk1** [comment]
You have to click where the handle is when the door is open (hidden below the door step)
You can lean out to see handle (if you have a handset or trackir)
